linters:
  enable:
    - bodyclose
    - dupl
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gocritic
    - gofumpt
    - gomnd
    - gomoddirectives
    - importas
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
#   - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
#    - thelper
    - unconvert
    - wastedassign
    - whitespace
    - wsl
    - forbidigo
linters-settings:
  gomnd:
    settings:
      mnd:
        ignored-functions: strconv.*
  tagliatelle:
    case:
      rules:
        json: snake
# ------ this is disable copylock errors
#  govet:
#    disable:
#      - copylocks
# ------
run:
  skip-dirs:
    - restapi
    - mock
issues:
  exclude:
    - Magic number
  exclude-rules:
    - path: cmd
      linters:
        - forbidigo
    - linters:
        - lll
      source: "^//go:generate "
